lang: en-US
timezone: America/Argentina/Buenos_Aires
# data-theme: dark # default theme "dark" | "light"

author:
  name: Domingo
  github: dmontoyaybarra # github username
  twitter: dmontoyaybarra # twitter username
  linkedin: dmontoyaybarra # linkedin profile

# Font Settings
googlewebfonts: family=Play:wght@400;700&family=Source+Code+Pro:ital,wght@0,200;0,300;0,400;0,600;0,700;0,900;1,300;1,400;1,500;1,600;1,700;1,900

# URL settings
baseurl: "" # sub folder for jekyll site. only if jekyll site not in root of host. leave blank if not wishd. always add / in front.
# permalink: pretty
permalink: /:title

# local
# url: "http://localhost:4000" # 
# baseurl: "" # 

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links

  


